/**
 * v0 UI Component (DO NOT MODIFY)
 * Generated by v0
 * Protected UI Layer
 */

type KpiCardAccent = "default" | "success" | "warn" | "danger"

type KpiCardProps = {
  label: string
  value: number
  subtitle?: string
  accent?: KpiCardAccent
}

const ACCENT_COLORS: Record<KpiCardAccent, string> = {
  default: "text-gray-900",
  success: "text-emerald-600",
  warn: "text-amber-600",
  danger: "text-red-600",
}

export default function KpiCard({
  label,
  value,
  subtitle,
  accent = "default",
}: KpiCardProps): JSX.Element {
  return (
    <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
      <p className="text-xs font-medium text-gray-500">{label}</p>
      {subtitle ? (
        <p className="mt-0.5 text-[10px] text-gray-400">{subtitle}</p>
      ) : null}
      <p
        className={`mt-1 text-2xl font-semibold tabular-nums ${ACCENT_COLORS[accent]}`}
      >
        {value.toLocaleString("ko-KR")}
      </p>
    </div>
  )
}
