/**
 * v0 UI Component (DO NOT MODIFY)
 * Generated by v0
 * Protected UI Layer
 */

import type { ReactNode } from "react";

export interface PageHeaderProps {
  eyebrow?: string;
  title: string;
  description?: string;
  /**
   * Optional right-aligned slot (e.g. badge, small CTA).
   */
  aside?: ReactNode;
  /**
   * Optional label style: "default" (light) or "inverted" for dark sections.
   */
  variant?: "default" | "inverted";
}

/**
 * Standard page/section heading block for non-hero marketing pages.
 * Visually aligned with v0 Metrics / HowItWorks headers.
 */
export function PageHeader({
  eyebrow,
  title,
  description,
  aside,
  variant = "default",
}: PageHeaderProps): JSX.Element {
  const isInverted = variant === "inverted";
  const eyebrowTextClass = isInverted
    ? "text-background/50"
    : "text-muted-foreground";
  const eyebrowLineClass = isInverted
    ? "bg-background/30"
    : "bg-foreground/30";
  const titleClass = isInverted
    ? "text-4xl lg:text-5xl font-display tracking-tight text-background"
    : "text-4xl lg:text-5xl font-display tracking-tight text-foreground";
  const descriptionClass = isInverted
    ? "text-sm lg:text-base text-background/70 leading-relaxed"
    : "text-sm lg:text-base text-muted-foreground leading-relaxed";

  return (
    <div className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-8 mb-12 lg:mb-16">
      <div>
        {eyebrow ? (
          <span className="inline-flex items-center gap-3 text-sm font-mono mb-5">
            <span className={`w-8 h-px ${eyebrowLineClass}`} />
            <span className={eyebrowTextClass}>{eyebrow}</span>
          </span>
        ) : null}
        <h2 className={titleClass}>{title}</h2>
        {description ? (
          <p className={`mt-4 max-w-xl ${descriptionClass}`}>{description}</p>
        ) : null}
      </div>
      {aside ? (
        <div className="flex-shrink-0">{aside}</div>
      ) : null}
    </div>
  );
}

