/**
 * v0 UI Component (DO NOT MODIFY)
 * Generated by v0
 * Protected UI Layer
 */

import type { ReactNode } from "react";

export interface SectionWrapperProps {
  children: ReactNode;
  /**
   * Optional id to link from navigation (e.g. #features, #how-it-works).
   */
  id?: string;
  /**
   * Optional additional classes to extend the base section styling.
   */
  className?: string;
}

/**
 * Shared section shell for marketing pages.
 * Matches v0 landing spacing and container width:
 * - py-24 lg:py-32
 * - max-w-[1400px] mx-auto
 * - px-6 lg:px-12
 */
export function SectionWrapper({
  children,
  id,
  className,
}: SectionWrapperProps): JSX.Element {
  return (
    <section
      id={id}
      className={[
        "py-24 lg:py-32",
        "border-0", // callers can override for bordered sections
        className ?? "",
      ]
        .filter(Boolean)
        .join(" ")}
    >
      <div className="max-w-[1400px] mx-auto px-6 lg:px-12">
        {children}
      </div>
    </section>
  );
}

