/**
 * v0 UI Component (DO NOT MODIFY)
 * Generated by v0
 * Protected UI Layer
 */

import type { ReactNode } from "react";

import { Navigation } from "@/components/landing/navigation";
import { FooterSection } from "@/components/landing/footer-section";

export interface MarketingShellProps {
  children: ReactNode;
}

/**
 * High-level marketing layout shell.
 * Mirrors the v0 landing structure: fixed navigation, centered content width, and footer.
 */
export function MarketingShell({
  children,
}: MarketingShellProps): JSX.Element {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <Navigation />
      <main className="pt-24 pb-16">
        <div className="max-w-[1400px] mx-auto px-6 lg:px-12">
          {children}
        </div>
      </main>
      <FooterSection />
    </div>
  );
}

