/**
 * v0 UI Component (DO NOT MODIFY)
 * Generated by v0
 * Protected UI Layer
 */

export default function AdminBadge(): JSX.Element {
  return (
    <span className="inline-block rounded bg-indigo-100 px-1.5 py-0.5 text-[10px] font-semibold text-indigo-700">
      Admin
    </span>
  );
}
