/**
 * v0 UI Component (DO NOT MODIFY)
 * Generated by v0
 * Protected UI Layer
 */

import type { ReactNode } from "react";

export interface FeatureCardProps {
  title: string;
  description: string;
  /**
   * Optional small label above the title.
   */
  label?: string;
  /**
   * Optional icon or glyph in the top-left.
   */
  icon?: ReactNode;
  /**
   * Optional footer content (e.g. small link or meta).
   */
  footer?: ReactNode;
}

/**
 * Marketing feature card aligned to v0 landing cards:
 * - rounded-2xl
 * - subtle border with foreground/10
 * - light shadow and neutral background
 */
export function FeatureCard({
  title,
  description,
  label,
  icon,
  footer,
}: FeatureCardProps): JSX.Element {
  return (
    <article className="relative rounded-2xl border border-foreground/10 bg-background/80 shadow-sm hover:shadow-md transition-shadow duration-200">
      <div className="p-6 lg:p-8 space-y-4">
        {label ? (
          <p className="text-xs font-mono uppercase tracking-[0.16em] text-muted-foreground">
            {label}
          </p>
        ) : null}
        <div className="flex items-start gap-4">
          {icon ? (
            <div className="mt-1 flex h-9 w-9 items-center justify-center rounded-full bg-foreground/5 text-foreground/80">
              {icon}
            </div>
          ) : null}
          <div>
            <h3 className="text-base lg:text-lg font-semibold text-foreground">
              {title}
            </h3>
            <p className="mt-2 text-sm text-muted-foreground leading-relaxed">
              {description}
            </p>
          </div>
        </div>
        {footer ? (
          <div className="pt-3 border-t border-foreground/5 text-xs text-muted-foreground">
            {footer}
          </div>
        ) : null}
      </div>
    </article>
  );
}

