/**
 * v0 UI Component (DO NOT MODIFY)
 * Generated by v0
 * Protected UI Layer
 */

type SkeletonCardProps = {
  lines?: number;
  className?: string;
};

function SkeletonLine({ width }: { width: string }): JSX.Element {
  return (
    <div
      className={`h-3 animate-pulse rounded-md bg-gray-200 ${width}`}
    />
  );
}

export default function SkeletonCard({
  lines = 3,
  className = "",
}: SkeletonCardProps): JSX.Element {
  const widths = ["w-3/4", "w-full", "w-5/6", "w-2/3", "w-4/5"];

  return (
    <div
      className={`rounded-xl border border-gray-200 bg-white p-5 shadow-sm sm:p-6 ${className}`}
    >
      <div className="mb-4 h-4 w-1/3 animate-pulse rounded-md bg-gray-200" />
      <div className="space-y-3">
        {Array.from({ length: lines }, (_, i) => (
          <SkeletonLine key={i} width={widths[i % widths.length]} />
        ))}
      </div>
    </div>
  );
}

export function SkeletonMetricsGrid(): JSX.Element {
  return (
    <div className="grid grid-cols-2 gap-2.5 sm:grid-cols-3 sm:gap-3 lg:grid-cols-4 xl:grid-cols-5">
      {Array.from({ length: 9 }, (_, i) => (
        <div
          key={i}
          className="rounded-xl border border-gray-200 bg-white p-3.5 sm:p-4"
        >
          <div className="mb-2 h-3 w-16 animate-pulse rounded bg-gray-200" />
          <div className="mb-1.5 h-6 w-20 animate-pulse rounded bg-gray-200" />
          <div className="h-2.5 w-24 animate-pulse rounded bg-gray-100" />
        </div>
      ))}
    </div>
  );
}

export function SkeletonScoreSection(): JSX.Element {
  return (
    <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm sm:p-6">
      <div className="mb-4 h-4 w-28 animate-pulse rounded bg-gray-200" />
      <div className="flex flex-col gap-6 lg:flex-row lg:items-start">
        <div className="flex flex-col items-center lg:w-40">
          <div className="h-14 w-14 animate-pulse rounded-xl bg-gray-200" />
          <div className="mt-2 h-3 w-12 animate-pulse rounded bg-gray-100" />
        </div>
        <div className="flex-1 space-y-4">
          {Array.from({ length: 5 }, (_, i) => (
            <div key={i}>
              <div className="mb-1.5 flex justify-between">
                <div className="h-3 w-20 animate-pulse rounded bg-gray-200" />
                <div className="h-3 w-8 animate-pulse rounded bg-gray-200" />
              </div>
              <div className="h-2 w-full animate-pulse rounded-full bg-gray-100" />
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export function SkeletonRadar(): JSX.Element {
  return (
    <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm sm:p-6">
      <div className="mb-4 h-4 w-32 animate-pulse rounded bg-gray-200" />
      <div className="mx-auto h-64 w-64 animate-pulse rounded-full bg-gray-100 sm:h-80 sm:w-80" />
    </div>
  );
}

export function SkeletonInsightSection(): JSX.Element {
  return (
    <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm sm:p-6">
      <div className="mb-4 h-4 w-24 animate-pulse rounded bg-gray-200" />
      <div className="space-y-2.5">
        {Array.from({ length: 3 }, (_, i) => (
          <div
            key={i}
            className="rounded-xl border border-gray-100 bg-gray-50 px-4 py-3"
          >
            <div className={`h-3 animate-pulse rounded bg-gray-200 ${i === 0 ? "w-full" : i === 1 ? "w-5/6" : "w-4/5"}`} />
          </div>
        ))}
      </div>
    </div>
  );
}

export function AnalysisReportSkeleton(): JSX.Element {
  return (
    <div className="space-y-8">
      <SkeletonCard lines={2} />
      <SkeletonMetricsGrid />
      <SkeletonScoreSection />
      <SkeletonRadar />
      <SkeletonCard lines={4} />
      <div className="grid gap-6 xl:grid-cols-2">
        <SkeletonInsightSection />
        <SkeletonInsightSection />
      </div>
      <SkeletonInsightSection />
    </div>
  );
}
